version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysqldb
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: user123
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
